apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethercalc
  labels:
    app: ethercalc
spec:
  replicas: 1
  # Keep record of 2 revisions for rollback
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ethercalc
    spec:
      containers:
      - name: ethercalc
        image: audreyt/ethercalc:latest
        ports: 
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: ethercalc
  labels:
    app: ethercalc
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: ethercalc
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        command:
        - redis-server 
        - --appendonly yes
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
